[package]
name = "rs-co2mon"
version = "0.1.0"
authors = ["Vitold S. <vit1251@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.3.2"